name: BoxOfBits
version: 1.2.3
author: BoxOfDevs Team
authors:
- TheDragonRing
- Taki21
- Ad5001
- remotevase
- Vaivez66
- 0-Eclipse-0
api:
- 1.14.0
- 2.0.0
main: BoxOfBits\Loader
commands:
    boxofbits:
        usage: "/boxofbits"
        description: "View BoxOfBits info"
        permission: boxofbits.info
    message:
        usage: "/message <server|player> <message...>"
        description: "Send a message to either the whole server or one player"
        permission: boxofbits.msgs.message
    popup:
        usage: "/popup <server|player> <message...>"
        description: "Send a popup to either the whole server or one player"
        permission: boxofbits.msgs.popup
    tip:
        usage: "/tip <server|player> <message...>"
        description: "Send a tip to either the whole server or one player"
        permission: boxofbits.msgs.tip
    pm:
        usage: "/pm <player> <message...>"
        description: "Sends a private message"
        permission: boxofbits.msgs.pm
    gms:
        usage: "/gms [player]"
        description: "Changes gamemode to Survival"
        permission: boxofbits.gm.gms
    gmc:
        usage: "/gmc [player]"
        description: "Changes gamemode to Creative"
        permission: boxofbits.gm.gmc
    gma:
        usage: "/gma [player]"
        description: "Changes gamemode to Adventure"
        permission: boxofbits.gm.gma
    gmsp:
        usage: "/gmsp [player]"
        description: "Changes gamemode to Spectator"
        permission: boxofbits.gm.gmsp
    xyz:
        usage: "/xyz [player]"
        description: "Get xyz coordinates"
        permission: boxofbits.xyz
    rules:
        usage: "/rules"
        description: "Shows the server rules"
        permission: boxofbits.rules
    suicide:
        usage: "/suicide"
        description: "Kill yourself"
        permission: boxofbits.hm.suicide
    slay:
        usage: "/slay <player>"
        description: "Kills player"
        permission: boxofbits.hm.slay
    heal:
        usage: "/heal [player]"
        description: "Heals you or specified player"
        permission: boxofbits.hm.heal
    health:
        usage: "/health <amount> [player]"
        description: "Sets your or players health"
        permission: boxofbits.hm.health
    fly:
        usage: "/fly [player]"
        description: "Lets a player fly in survival"
        permission: boxofbits.fly
    hidetag:
        usage: "/hidetag <on|off>"
        description: "Hides the nametag above your head"
        permission: boxofbits.name.ht
    nick:
        usage: "/nick <nickname|reset>"
        description: "Changes your display name"
        permission: boxofbits.name.nick
    wild:
        usage: "/wild [player]"
        description: "Teleports to a random place"
        permission: boxofbits.tp.wild
    setperm:
        usage: "/setperm <player> <permission>"
        description: "Give a player a permission"
        permission: boxofbits.pm.setperm
    rmperm:
        usage: "/rmperm <player> <permission>"
        description: "Removes a players permission"
        permission: boxofbits.pm.rmperm
    hasperm:
        usage: "/hasperm <player> <permission>"
        description: "Checks if a player has a permission"
        permission: boxofbits.pm.hasperm
    seeperms:
        usage: "/seeperms <player>"
        description: "Shows a players permissions"
        permission: boxofbits.pm.seeperms
    allperms:
        usage: "/seeperms <player>"
        description: "Shows all possible permissions on the server"
        permission: boxofbits.pm.allperms
permissions:
    boxofbits:
        default: false
        children:
            boxofbits.info:
                default: true
            boxofbits.msgs:
                default: false
                children:
                    boxofbits.msgs.message:
                        default: op
                    boxofbits.msgs.popup:
                        default: op
                    boxofbits.msgs.tip:
                        default: op
                    boxofbits.msgs.pm:
                        default: true
            boxofbits.gm:
                default: false
                children:
                    boxofbits.gm.gms:
                        default: op
                    boxofbits.gm.gmc:
                        default: op
                    boxofbits.gm.gma:
                        default: op
                    boxofbits.gm.gmsp:
                        default: op
            boxofbits.xyz:
                default: true
            boxofbits.rules:
                default: true
            boxofbits.hm:
                default: false
                children:
                    boxofbits.hm.suicide:
                        default: true
                    boxofbits.hm.slay:
                        default: op
                    boxofbits.hm.heal:
                        default: op
                    boxofbits.hm.health:
                        default: op
            boxofbits.fly:
                default: op
            boxofbits.name:
                default: false
                children:
                    boxofbits.name.ht:
                        default: op
                    boxofbits.name.nick:
                        default: op
            boxofbits.allowcolour:
                default: false
                children:
                    boxofbits.allowcolour.chat:
                        default: op
                    boxofbits.allowcolour.sign:
                        default: op
            boxofbits.tp:
                default: false
                children:
                    boxofbits.tp.wild:
                        default: true
            boxofbits.pm:
                default: false
                children:
                    boxofbits.pm.setperm:
                        default: op
                    boxofbits.pm.rmperm:
                        default: op
                    boxofbits.pm.hasperm:
                        default: op
                    boxofbits.pm.seeperms:
                        default: op
                    boxofbits.pm.hasperms:
                        default: op
