BroadcastSettings:
    Enabled: Yes
    Type: Message
    Prefix: "[ServerName]"
    SecondsBetweenBroadcast: 30

Broadcasts:
    - "Random Broadcast!"
    - "Other Random Broadcast!"
    - "Another Random Broadcast!"
    - "Yet Again, A Random Broadcast!"
    - "Why So Many Random Broadcasts?"
