---

#  ____             ____   __ ____  _ _              __  __   ___  
# |  _ \           / __ \ / _|  _ \(_) |            /_ |/_ | / _ \ 
# | |_) | _____  _| |  | | |_| |_) |_| |_ ___  __   _| | | || | | |
# |  _ < / _ \ \/ / |  | |  _|  _ <| | __/ __| \ \ / / | | || | | |
# | |_) | (_) >  <| |__| | | | |_) | | |_\__ \  \ V /| |_| || |_| |
# |____/ \___/_/\_\\____/|_| |____/|_|\__|___/   \_/ |_(_)_(_)___/ 
#                                                                    
                                      
# Custom messages which either get sent in chat or popup on the bottom of the screen when certain events occur
# Please note that the JoinMessage and LeaveMessage replace the default join and leave/quit messages
# Use #playername as the name of the player and § to colour the text
JoinMessage: "#playername §bJoined the Server"
JoinPopup: "#playername §bJoined the Server"
LeaveMessage: "#playername §4Left the Server"
LeavePopup: "#playername §4Left the Server"
KickPopup: "#playername §4Got Kicked from the Server"
GamemodeChangePopup: "#playername §2Changed Gamemode"
DeathPopup: "#playername §4Just Died"

# Custom rules which show up when /rules 1|2 is run
# Use § to colour the text
Rule1: "No Swearing"
Rule2: "No Using Mods"
Rule3: "No Advertising"
Rule4: "No Asking For OP"
Rule5: "No Asking For Creative"
Rule6: "Have Fun :)"
Rule7: "No Griefing"
Rule8: "Another Rule"
Rule9: "Another Rule"
Rule10: "Another Rule"
...
